### ISSUE TITLE
Improve speed of fetching citation information

### ISSUE THREAD

**Issue by andrewhead** [allenai/scholarphi#84]
It takes a minute or so to fetch the abstracts and titles for all of the cited papers, the first time a specific arXiv paper is opened in the interactive reader, or the first time a paper is accessed after the API is restarted.

This is because the API fetches abstract and title information from the S2 API, and for the typical paper, needs to request summary information for dozens of papers. These requests take some time.

The interface makes it look like there's no data for a cited paper when the API is taking as long as it does to fetch paper details, showing this message:

![image](https://user-images.githubusercontent.com/2358524/77778605-7e5b7f00-700e-11ea-9638-53d2f24c96a4.png)

To solve this issue, the API should be updated to fetch paper details more quickly. Potential solutions include:

* Pre-fetching paper details for a large number of cited papers
* Uploading paper details to the database as part of the pipeline, and joining on a paper details table when fetching citations

**Comment by mjlangan** [comment]
The UI could also display a loading spinner to more clearly indicate there's an in-flight request
